// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dart_value.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`

BTreeMapStringValue hashmapToBtreemap({
  required Map<String, DartValue> hashmap,
}) => RustLib.instance.api.crateDartValueConversionHashmapToBtreemap(
  hashmap: hashmap,
);

BTreeMapStringDartValue hashmapToBtreemapDartValue({
  required Map<String, DartValue> hashmap,
}) => RustLib.instance.api.crateDartValueConversionHashmapToBtreemapDartValue(
  hashmap: hashmap,
);

Map<String, DartValue> btreemapToHashmap({
  required BTreeMapStringValue btreemap,
}) => RustLib.instance.api.crateDartValueConversionBtreemapToHashmap(
  btreemap: btreemap,
);

Map<String, DartValue> btreemapToHashmapDartValue({
  required BTreeMapStringDartValue btreemap,
}) => RustLib.instance.api.crateDartValueConversionBtreemapToHashmapDartValue(
  btreemap: btreemap,
);

BTreeMapStringValue btreemapDartValueToBtreemap({
  required BTreeMapStringDartValue btreemap,
}) => RustLib.instance.api.crateDartValueConversionBtreemapDartValueToBtreemap(
  btreemap: btreemap,
);

BTreeMapStringDartValue btreemapToBtreemapDartValue({
  required BTreeMapStringValue btreemap,
}) => RustLib.instance.api.crateDartValueConversionBtreemapToBtreemapDartValue(
  btreemap: btreemap,
);
