// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dart_value.dart';
import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'function.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`

@freezed
sealed class DartFunctionResult with _$DartFunctionResult {
  const DartFunctionResult._();

  /// The Convex value returned on a successful run of a Convex function
  const factory DartFunctionResult.value(DartValue field0) =
      DartFunctionResult_Value;

  /// The error message of a Convex function run that does not complete
  /// successfully.
  const factory DartFunctionResult.errorMessage(String field0) =
      DartFunctionResult_ErrorMessage;

  /// The error payload of a Convex function run that doesn't complete
  /// successfully, with an application-level error.
  const factory DartFunctionResult.convexError(DartConvexError field0) =
      DartFunctionResult_ConvexError;
}
