targets:
  $default:
    builders:
      convex_dart_builder:
        generate_for:
          - lib/schema.json
        options:
          input_file: lib/schema.json
          mapping_file: lib/schema-mapping-fieldAgents.json
          objectbox_functions_file: lib/objectbox-functions-fieldAgents.json
      objectbox:objectbox_generator:
        enabled: true
