targets:
  $default:
    builders:
      convex_dart_builder:
        generate_for:
          - lib/schema.json
        options:
          input_file: lib/schema.json
          mapping_file: lib/schema-mapping-fieldAgent.json
      objectbox:objectbox_generator:
        enabled: true
