// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/objectbox/box/app_user_box.dart';
import 'src/models/objectbox/box/cash_count_field_sign_up_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 9091357545077996267),
    name: 'AppUserBox',
    lastPropertyId: const obx_int.IdUid(1, 5058715603306662646),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5058715603306662646),
        name: 'id',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5236815421559271578),
    name: 'CashCountFieldSignUpBox',
    lastPropertyId: const obx_int.IdUid(6, 4903768863996242175),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4838046608486599737),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3873946455964808670),
        name: 'lastSyncDate',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6780047985987102865),
        name: 'paginationOpts',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3645887995863265352),
        name: 'searchText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2990255451503922575),
        name: 'sortBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4903768863996242175),
        name: 'sortOrder',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 5236815421559271578),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      5022870615773346892,
      8975633203547562938,
      9211290216321051773,
      7831205287387523691,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3256565287644386649,
      1458517379962432625,
      6192686662487177426,
      7419373505000487634,
      2099913133662749044,
      5357143261249459454,
      7589914909337369379,
      6282874266279275361,
      3852644800045284492,
      99211308021360397,
      318054940154523975,
      3606902979306845820,
      2713122348611282843,
      2088901517833216825,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppUserBox: obx_int.EntityDefinition<AppUserBox>(
      model: _entities[0],
      toOneRelations: (AppUserBox object) => [],
      toManyRelations: (AppUserBox object) => {},
      getId: (AppUserBox object) => object.id,
      setId: (AppUserBox object, int id) {
        object.id = id;
      },
      objectToFB: (AppUserBox object, fb.Builder fbb) {
        fbb.startTable(2);
        fbb.addInt64(0, object.id);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = AppUserBox(id: idParam);

        return object;
      },
    ),
    CashCountFieldSignUpBox: obx_int.EntityDefinition<CashCountFieldSignUpBox>(
      model: _entities[1],
      toOneRelations: (CashCountFieldSignUpBox object) => [],
      toManyRelations: (CashCountFieldSignUpBox object) => {},
      getId: (CashCountFieldSignUpBox object) => object.id,
      setId: (CashCountFieldSignUpBox object, int id) {
        object.id = id;
      },
      objectToFB: (CashCountFieldSignUpBox object, fb.Builder fbb) {
        final paginationOptsOffset = object.paginationOpts == null
            ? null
            : fbb.writeString(object.paginationOpts!);
        final searchTextOffset = object.searchText == null
            ? null
            : fbb.writeString(object.searchText!);
        final sortByOffset = object.sortBy == null
            ? null
            : fbb.writeString(object.sortBy!);
        final sortOrderOffset = object.sortOrder == null
            ? null
            : fbb.writeString(object.sortOrder!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.lastSyncDate);
        fbb.addOffset(2, paginationOptsOffset);
        fbb.addOffset(3, searchTextOffset);
        fbb.addOffset(4, sortByOffset);
        fbb.addOffset(5, sortOrderOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final lastSyncDateParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final paginationOptsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final searchTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final sortByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final sortOrderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = CashCountFieldSignUpBox(
          id: idParam,
          lastSyncDate: lastSyncDateParam,
          paginationOpts: paginationOptsParam,
          searchText: searchTextParam,
          sortBy: sortByParam,
          sortOrder: sortOrderParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppUserBox] entity fields to define ObjectBox queries.
class AppUserBox_ {
  /// See [AppUserBox.id].
  static final id = obx.QueryIntegerProperty<AppUserBox>(
    _entities[0].properties[0],
  );
}

/// [CashCountFieldSignUpBox] entity fields to define ObjectBox queries.
class CashCountFieldSignUpBox_ {
  /// See [CashCountFieldSignUpBox.id].
  static final id = obx.QueryIntegerProperty<CashCountFieldSignUpBox>(
    _entities[1].properties[0],
  );

  /// See [CashCountFieldSignUpBox.lastSyncDate].
  static final lastSyncDate =
      obx.QueryDateNanoProperty<CashCountFieldSignUpBox>(
        _entities[1].properties[1],
      );

  /// See [CashCountFieldSignUpBox.paginationOpts].
  static final paginationOpts =
      obx.QueryStringProperty<CashCountFieldSignUpBox>(
        _entities[1].properties[2],
      );

  /// See [CashCountFieldSignUpBox.searchText].
  static final searchText = obx.QueryStringProperty<CashCountFieldSignUpBox>(
    _entities[1].properties[3],
  );

  /// See [CashCountFieldSignUpBox.sortBy].
  static final sortBy = obx.QueryStringProperty<CashCountFieldSignUpBox>(
    _entities[1].properties[4],
  );

  /// See [CashCountFieldSignUpBox.sortOrder].
  static final sortOrder = obx.QueryStringProperty<CashCountFieldSignUpBox>(
    _entities[1].properties[5],
  );
}
